[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"
authors = ["PDF Editor Team"]
license = "Apache-2.0"
description = "Rust backend for the Fabric.js/pdf.js powered PDF editor"

[dependencies]
anyhow = "1"
axum = { version = "0.6", features = ["macros", "json"] }
bytes = "1"
futures = "0.3"
harfbuzz_rs = "2"
lazy_static = "1"
dashmap = "5"
lopdf = { version = "0.32", default-features = false, features = ["flate2"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
ttf-parser = "0.19"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
uuid = { version = "1", features = ["v4", "serde"] }
base64 = "0.21"
