[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["PDF Editor Team"]
license = "Apache-2.0"
description = "Incremental PDF editor backend"

[dependencies]
axum = { version = "0.7", features = ["json", "multipart"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
anyhow = "1"
lopdf = "0.32"
harfbuzz_rs = "2"
ttf-parser = "0.19"
lazy_static = "1"
base64 = "0.21"
bytes = "1"
parking_lot = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
uuid = { version = "1", features = ["v4"] }
