[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Rust backend for a PDF editing web app"

[dependencies]
axum = { version = "0.7", features = ["json", "multipart"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
anyhow = "1"
lopdf = "0.32"
harfbuzz = "0.6"
ttf-parser = "0.22"
lazy_static = "1"
uuid = { version = "1", features = ["v4"] }
bytes = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
base64 = "0.21"
