[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"
authors = ["PDF Editor Authors"]
license = "Apache-2.0"

[dependencies]
axum = { version = "0.7", features = ["json", "multipart"] }
tokio = { version = "1.37", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.7"
thiserror = "1.0"
anyhow = "1.0"
lopdf = "0.32"
harfbuzz = "0.5"
ttf-parser = "0.21"
lazy_static = "1.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
uuid = { version = "1", features = ["v4", "serde"] }
parking_lot = "0.12"
base64 = "0.22"
bytes = "1.6"
