[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"
authors = ["PDF Editor Team"]
license = "Apache-2.0"

[dependencies]
axum = { version = "0.7", features = ["multipart"] }
anyhow = "1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3"
lopdf = "0.32"
harfbuzz = "0.6"
ttf-parser = "0.19"
lazy_static = "1"
bytes = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
uuid = { version = "1", features = ["v4", "serde"] }
base64 = "0.22"
futures = "0.3"
