[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["PDF Editor Authors"]
description = "Axum-based backend for a Fabric.js powered PDF editor"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3"
thiserror = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["serde", "v4"] }
parking_lot = "0.12"
bytes = "1"
base64 = "0.22"
# PDF + text stack
lopdf = { version = "0.32", default-features = false, features = ["chrono"] }
harfbuzz_rs = "2"
ttf-parser = "0.20"

[dev-dependencies]
serde_json = "1"
