[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["PDF Editor Team"]

[dependencies]
anyhow = "1.0"
axum = { version = "0.7", features = ["multipart"] }
bytes = "1.5"
harfbuzz = { package = "harfbuzz_rs", version = "2.0" }
lazy_static = "1.4"
lopdf = "0.32"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.36", features = ["rt-multi-thread", "macros"] }
ttf-parser = "0.21"
uuid = { version = "1.7", features = ["v4"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
