[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"
authors = ["PDF Editor Authors"]
license = "Apache-2.0"

[dependencies]
axum = { version = "0.7", features = ["json"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
anyhow = "1"
lopdf = "0.30"
harfbuzz_rs = "2.0"
ttf-parser = "0.20"
lazy_static = "1"
parking_lot = "0.12"
uuid = { version = "1", features = ["v4", "serde"] }
bytes = "1"
