[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["PDF Editor Authors"]

[dependencies]
axum = { version = "0.7", features = ["multipart"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
thiserror = "1"
anyhow = "1"
lopdf = "0.32"
harfbuzz = "0.6"
ttf-parser = "0.19"
lazy_static = "1"
bytes = "1"
uuid = { version = "1", features = ["v4"] }
tempfile = "3"
parking_lot = "0.12"
base64 = "0.22"
