[package]
name = "pdf-editor-backend"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread"] }
thiserror = "1.0"
anyhow = "1.0"
lopdf = "0.32"
harfbuzz_rs = "2.0"
ttf-parser = "0.20"
lazy_static = "1.4"
uuid = { version = "1.7", features = ["v4"] }
base64 = "0.21"

[dev-dependencies]
serde_json = "1.0"
