[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"
authors = ["PDF Editor Contributors"]
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
axum = { version = "0.7", features = ["multipart"] }
bytes = "1.5"
futures = "0.3"
harfbuzz = "0.6"
lazy_static = "1.4"
lopdf = "0.32"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.34", features = ["rt-multi-thread", "macros"] }
ttf-parser = "0.20"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
base64 = "0.21"
uuid = { version = "1.6", features = ["v4"] }
