[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2024"
authors = ["PDF Editor Contributors"]
description = "Axum-based backend for the Fabric PDF editor"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
axum = { version = "0.7", features = ["macros", "multipart"] }
base64 = "0.22"
futures = "0.3"
harfbuzz = { package = "harfbuzz_rs", version = "2.0" }
lazy_static = "1.4"
lopdf = "0.32"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread"] }
ttf-parser = "0.20"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
uuid = { version = "1.8", features = ["v4"] }
