[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Axum backend for the PDF editor"

[dependencies]
axum = { version = "0.7", features = ["multipart"] }
tokio = { version = "1.36", features = ["rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
thiserror = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }
bytes = "1"
parking_lot = "0.12"
lopdf = "0.32"
harfbuzz = { package = "harfbuzz", version = "0.5" }
ttf-parser = "0.20"
lazy_static = "1"
base64 = "0.22"
include_dir = "0.7"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
