[package]
name = "pdf-editor-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
axum = { version = "0.7", features = ["json", "multipart"] }
bytes = "1.5"
lazy_static = "1.4"
lopdf = "0.32"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.35", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1.6", features = ["v4"] }
base64 = "0.21"
harfbuzz_rs = "2.0"
ttf-parser = "0.20"
log = "0.4"
